### PR TITLE
Add fighter command

### PR DESCRIPTION
**Pull request by terry-wilkerson**
added a command to spawn fighters in the players hanger.

### CODE REVIEW

**Comment by mark-kubacki** [comment]
Barrenn, your script has contraband: it duplicates parts of another script. Please either submit this as completely new command (`require` the file with any tables you need), or modify the current one (`inventory.lua`).

The many indentation levels can easily be avoided by checking for undesired states first to return early. For example:

```diff
-if ship:hasComponent(ComponentType.Hangar) then
-	if … then
-		stuff;
-	end
-end
+if not ship:hasComponent(ComponentType.Hangar) then
+	return false, err
+end
+if not … then
+	return false, err
+end
+
+stuff;
+return true, ""
```

… which is part of a good programming style that results in maintainability.

**Comment by nthirtyone** [comment]
I have rebased it to `new-commands`. Only fixed readme file conflicts. Some of the functions and variables are not needed at this point and can be obtained from `scripts/lib/cmd/`, where our common files are located.
Same goes for `available` which was moved into completely separate command `/list`.

**Review by mark-kubacki — CHANGES_REQUESTED** [review]
Please sync your README.md with the most recent one (Aki has already provided an example which lines to change.)

Please use one indentation style exclusively (fighter.lua). (No mixed tabs and spaces, please. Yes, we messed that up too.)

`require` the file with the tables you need, and squash all those `if` as outlined in my above comment.

You can `git push … +AddFighterCommand` later to overwrite your branch in case you want to `git checkout AddFighterCommand && git rebase master` and/or `git rebase -i HEAD~2` to amend or squash previous commits into clean new ones.

**Comment by mark-kubacki** [comment]
LGTM, would squash and merge.

**Review by mark-kubacki — APPROVED** [review]

**Comment by mark-kubacki** [comment]
@Barrenn thanks for your work!

**Pull request merged**
